POST http://localhost:3000/book/
Content-Type: application/json

{
  "title": "Maestro",
  "author": "Toni Kroos"
}

### Test GET API - Retrieve All Books
GET http://localhost:3000/books/

### Test GET API - Retrieve a Book by ID
GET http://localhost:3000/book/1

### update the book
PUT http://localhost:3000/book/10
Content-Type: application/json

{
  "title":"Legend",
  "author":"Modric"
}

### searching

GET http://localhost:3000/book1/?offset=5&limit=5&order=ASC&order_by=book_id


### Authentication
POST http://localhost:3000/user/
Content-Type:application/json

{
  "name":"Rahul",
  "username":"Rahul7",
  "location":"Kurnool",
  "password":"Rahul@1234"
}